### ISSUE TITLE
Error during creating AMI through CLI

### ISSUE THREAD

**Issue by andrzej-jedrzejewski** [cornfeedhobo/packer-virtualbox-ami-centos7#1]
Hi,

I got following error when I'am trying export sth else ext4:
{
    "ImportImageTasks": [
        {
            "Status": "deleted",
            "Description": "Centos 7.2 OVA with btrfs",
            "Platform": "Linux",
            "Architecture": "x86_64",
            "SnapshotDetails": [
                {
                    "UserBucket": {
                        "S3Bucket": "andrzejjbucket",
                        "S3Key": "centos7-lvm-btrfs.ova"
                    },
                    "DiskImageSize": 736849408.0,
                    "Format": "VMDK"
                }
            ],
            "StatusMessage": "ClientError: Unknown OS / Missing OS files.",
            "ImportTaskId": "import-ami-ffg9yygm"
        }
    ]
}
What version of packer and virtualbox you use?

**Comment by cornfeedhobo** [comment]
0.8.6
I had some cleanups lingering that I hadn't committed yet. Sorry to say, but `cloudinit` doesn't support btrfs anymore, so I removed it.
As for that error, I have no idea why you would have received it.
